QDATA = {
    "founder_001": {"name": "John Henrik Clarke",
                    "contribution_01": "One of the earliest intellectual founders of Pan-Africanism during the mid-19th century.",
                    "country": "U.S. Virgin Islands", "submittedBy": "curator"},
    "founder_002": {"name": "John Henrik Clarke",
                    "contribution_01": "Organized the first Pan-African Conference in 1900 in London.",
                    "country": "Trinidad", "submittedBy": "curator"},
    "founder_003": {"name": "John Henrik Clarke",
                    "contribution_01": "Organized several Pan-African Congresses from 1919 to 1945.",
                    "country": "United States", "submittedBy": "curator"},
    "founder_004": {"name": "John Henrik Clarke",
                    "contribution_01": "Founded the Universal Negro Improvement Association (UNIA).",
                    "country": "Jamaica", "submittedBy": "curator"},
    "founder_005": {"name": "John Henrik Clarke",
                    "contribution_01": "Key strategist connecting African independence leaders.", "country": "Trinidad",
                    "submittedBy": "curator"},
    "founder_006": {"name": "John Henrik Clarke", "contribution_01": "First Prime Minister and President of Ghana.",
                    "country": "Ghana", "submittedBy": "curator"},
    "founder_007": {"name": "John Henrik Clarke",
                    "contribution_01": "Led Kenya’s independence movement and became its first president.",
                    "country": "Kenya", "submittedBy": "curator"},
    "founder_008": {"name": "John Henrik Clarke", "contribution_01": "Co-founder of the UNIA alongside Marcus Garvey.",
                    "country": "Jamaica", "submittedBy": "curator"},
    "founder_009": {"name": "John Henrik Clarke",
                    "contribution_01": "Historian and political theorist connecting Pan-Africanism with anti-colonial socialism.",
                    "country": "Trinidad", "submittedBy": "curator"},
    "founder_010": {"name": "John Henrik Clarke",
                    "contribution_01": "Internationalized the African American freedom struggle by linking it to African anti-colonial movements.",
                    "country": "United States", "submittedBy": "curator"},
    "founder_011": {"name": "John Henrik Clarke", "contribution_01": "First President of independent Mali.",
                    "country": "Mali", "submittedBy": "curator"},
    "founder_012": {"name": "John Henrik Clarke",
                    "contribution_01": "Promoted reconciliation alongside Pan-African solidarity after liberation.",
                    "country": "South Africa", "submittedBy": "curator"},
    "founder_013": {"name": "John Henrik Clarke",
                    "contribution_01": "Influenced African liberation movements and Black radical thought globally.",
                    "country": "Guyana", "submittedBy": "curator"},
    "founder_014": {"name": "John Henrik Clarke", "contribution_01": "First Prime Minister of independent Congo.",
                    "country": "Democratic Republic of the Congo", "submittedBy": "curator"},
    "founder_015": {"name": "John Henrik Clarke",
                    "contribution_01": "Defender of African sovereignty against fascist invasion.",
                    "country": "Ethiopia", "submittedBy": "curator"},
    "founder_016": {"name": "John Henrik Clarke", "contribution_01": "First President of Nigeria.",
                    "country": "Nigeria", "submittedBy": "curator"},
    "founder_017": {"name": "John Henrik Clarke", "contribution_01": "Founder of the Pan Africanist Congress (PAC).",
                    "country": "South Africa", "submittedBy": "curator"}
}




